//! Walk the pinned checkout and establish what is actually in it.
//!
//! This is where the denominator is born, so it is the module with the most
//! defensive posture in the crate.
//!
//! WPT does not commit a test manifest - `MANIFEST.json` is generated by the
//! `wpt` tooling and absent from the repository at the pinned revision (verified
//! against the GitHub tree API). So the population of "tests" has to be derived,
//! and a derived population is a claim that has to be stated, not assumed.
//! [`Population`] is therefore explicit about every exclusion it makes, the
//! caller reports the sizes of the excluded buckets alongside the included one,
//! and [`verify_population_rule`] cross-checks the structural signal (a file
//! that something else `link rel="match"`es) against the naming convention
//! (`*-ref.html`) so a reader can see whether the cheap rule and the careful
//! rule agree.
//!
//! Two rules govern what may be claimed:
//!
//! * A file is only called *executable* when nothing was found that would stop
//!   it running. Absence of a known blocker is not proof of runnability, so
//!   unscannable files get their own bucket and are never folded into the
//!   executable count.
//! * Excluding a file is never the same as passing it. Every excluded file is
//!   counted, with a reason.

use std::collections::{BTreeMap, BTreeSet};
use std::fs;
use std::path::{Path, PathBuf};

use crate::classify::{self, Blocker, Capability, Classification, HarnessShape};
use crate::source;

/// Convert a `usize` count to the `u32` the result types use.
///
/// Saturating, not `as`: a truncating cast on a count turns a too-large
/// population into a *smaller plausible* one, and a denominator that shrinks
/// without anything failing is the exact failure this crate exists to prevent.
/// Saturating means the number is wrong in the visible direction instead.
fn count(value: usize) -> u32 {
    u32::try_from(value).unwrap_or(u32::MAX)
}

/// A checkout at a pinned revision.
#[derive(Debug, Clone)]
pub struct Suite {
    pub root: PathBuf,
    pub revision: String,
}

impl Suite {
    /// Open a checkout, refusing anything that is not a verified pinned tree.
    ///
    /// The `.pinned-revision` file is written by `tools/wpt/fetch-wpt.ps1` next
    /// to the tree. A checkout without it has not been verified, and running
    /// against an unverified checkout is how a number gets recorded against a
    /// suite nobody can name.
    pub fn open(root: impl Into<PathBuf>, expected_revision: &str) -> Result<Self, String> {
        let root = root.into();
        let pin = root.join(".pinned-revision");
        let recorded = fs::read_to_string(&pin)
            .map_err(|e| format!("no verified checkout at {}: {e}", root.display()))?
            .trim()
            .to_ascii_lowercase();
        if recorded != expected_revision.to_ascii_lowercase() {
            return Err(format!(
                "checkout at {} is pinned to {recorded}, not {expected_revision}",
                root.display()
            ));
        }
        // `common/` and `fonts/` are not test areas; they are shared helpers that
        // css/ and html/ reference with rooted URLs, and they must be present for
        // "missing fixture" to mean what it says.
        for tree in ["css", "dom", "html", "resources", "common", "fonts"] {
            if !root.join(tree).is_dir() {
                return Err(format!(
                    "checkout at {} is missing the {} tree; the fetch is incomplete",
                    root.display(),
                    tree
                ));
            }
        }
        let suite = Self { root, revision: recorded };
        assert_cache_not_nested(&suite)?;
        Ok(suite)
    }
}

/// Why a `.html` file in the tree is not a scored test.
impl std::fmt::Display for Exclusion {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(self.label())
    }
}

#[derive(Clone, Copy, Debug, PartialEq, Eq, PartialOrd, Ord)]
pub enum Exclusion {
    /// The target of some other file's `link rel="match"`: a reftest reference,
    /// not a test in its own right.
    Reference,
    /// Under a `support/` directory: a fixture, not a test.
    Support,
    /// Under a `manual/` directory: not an automated test by WPT's own rule.
    Manual,
    /// Under a `tools/` directory: suite tooling, not a test.
    Tooling,
    /// Unreadable as UTF-8, so nothing can be claimed about it. Reported, never
    /// silently dropped.
    Unreadable,
    /// In an area excluded by deliberate scope decision. Each scope decision is
    /// its own variant so the count can be argued with.
    OutOfScopeCanvas,
    OutOfScopeBrowsers,
}

impl Exclusion {
    pub const fn label(self) -> &'static str {
        match self {
            Self::Reference => "reference",
            Self::Support => "support-fixture",
            Self::Manual => "manual",
            Self::Tooling => "tooling",
            Self::Unreadable => "unreadable",
            Self::OutOfScopeCanvas => "out-of-scope-canvas",
            Self::OutOfScopeBrowsers => "out-of-scope-browsers",
        }
    }
}

/// The grouping key for a [`Blocker`], so counts aggregate by cause and not by
/// message.
#[derive(Clone, Copy, Debug, PartialEq, Eq, PartialOrd, Ord)]
pub enum BlockerKey {
    NoAssertions,
    MissingEngine(Capability),
    UnsupportedShape(HarnessShape),
    MissingFixture,
    Unscannable,
}

impl BlockerKey {
    pub const fn of(blocker: &Blocker) -> Self {
        match blocker {
            Blocker::NoAssertions => Self::NoAssertions,
            Blocker::MissingEngine(c) => Self::MissingEngine(*c),
            Blocker::UnsupportedShape(s) => Self::UnsupportedShape(*s),
            Blocker::MissingFixture(_) => Self::MissingFixture,
            Blocker::Unscannable(_) => Self::Unscannable,
        }
    }

    pub fn describe(self) -> String {
        match self {
            Self::NoAssertions => Blocker::NoAssertions.describe(),
            Self::MissingEngine(c) => Blocker::MissingEngine(c).describe(),
            Self::UnsupportedShape(s) => Blocker::UnsupportedShape(s).describe(),
            Self::MissingFixture => Blocker::MissingFixture(String::new()).describe(),
            Self::Unscannable => {
                Blocker::Unscannable("see details".to_owned()).describe()
            }
        }
    }
}

/// The shape of the test population, with every excluded bucket sized.
#[derive(Clone, Debug, Default)]
pub struct Population {
    /// `.html` files present in the area, before any exclusion.
    pub files_present: u32,
    /// Files in the scored test population.
    pub tests: u32,
    /// Exclusions by cause, so the arithmetic back to `files_present` closes.
    pub excluded: BTreeMap<Exclusion, u32>,
    /// Whether the naming convention and the structural signal agreed.
    pub reference_rule_agreement: Option<ReferenceRuleAgreement>,
    /// Messages for the individually interesting excluded files: unreadable
    /// files, missing fixtures, unscannable files. These are the ones a person
    /// has to look at, so they are not aggregated into a count.
    pub notable: Vec<Notable>,
}

/// How the cheap `*-ref.html` naming rule compared with the careful
/// "is something `rel=match`ing this?" rule.
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq)]
pub struct ReferenceRuleAgreement {
    /// Files some other file `rel=match`es.
    pub structurally_a_reference: u32,
    /// Files whose name ends in `-ref.html` or `.ref.html`.
    pub named_like_a_reference: u32,
    /// In both sets.
    pub in_both: u32,
    /// Structurally a reference but not named like one: the naming rule would
    /// have scored a reference as a test.
    pub missed_by_name: u32,
    /// Named like a reference but not structurally one: the naming rule would
    /// have dropped a real test.
    pub over_dropped_by_name: u32,
}

/// A single file a person needs to look at, with the reason.
#[derive(Clone, Debug)]
pub struct Notable {
    pub path: String,
    pub reason: String,
}

/// One area's census.
#[derive(Clone, Debug, Default)]
pub struct AreaCensus {
    pub area: String,
    pub population: Population,
    /// Files classified as executable: no known blocker found.
    pub executable: u32,
    /// Files that declare no assertion and no reftest reference, so they have no
    /// way to fail. Counted, and never scored.
    pub cannot_fail: u32,
    /// Blocked files by cause.
    pub blockers: BTreeMap<BlockerKey, u32>,
    /// Harness shape occurrences across the test population.
    pub shapes: BTreeMap<HarnessShape, u32>,
    /// Capability requirements across the test population.
    pub capabilities: BTreeMap<Capability, u32>,
    /// Assertion call sites found in the test population. A bound, not a count
    /// of assertions that were evaluated.
    pub assertion_sites: u64,
    /// Total bytes of test source classified.
    pub source_bytes: u64,
}

impl AreaCensus {
    /// Tests that produced a verdict, whether the verdict was executable or
    /// blocked. This is the denominator for a feasibility rate.
    pub const fn classified(&self) -> u32 {
        self.executable
    }

    /// A feasibility rate. It is a rate over *static classification*, not over
    /// engine behaviour, and the label says so.
    pub fn feasibility_rate(&self) -> Option<crate::outcome::Rate> {
        if self.population.tests == 0 {
            return None;
        }
        Some(crate::outcome::Rate {
            numerator: self.executable,
            denominator: self.population.tests,
        })
    }
}

/// The census for a set of areas.
#[derive(Clone, Debug, Default)]
pub struct Census {
    pub suite_revision: String,
    pub areas: Vec<AreaCensus>,
    pub total_files_present: u32,
    pub total_tests: u32,
    pub total_executable: u32,
    pub total_cannot_fail: u32,
}

impl Census {
    #[must_use]
    pub fn area(&self, name: &str) -> Option<&AreaCensus> {
        self.areas.iter().find(|a| a.area == name)
    }
}

/// Classify every test in the named areas.
pub fn run(suite: &Suite, areas: &[&str]) -> Result<Census, String> {
    let mut census = Census {
        suite_revision: suite.revision.clone(),
        ..Census::default()
    };
    for area in areas {
        let area_census = census_area(suite, area)?;
        census.total_files_present += area_census.population.files_present;
        census.total_tests += area_census.population.tests;
        census.total_executable += area_census.executable;
        census.total_cannot_fail += area_census.cannot_fail;
        census.areas.push(area_census);
    }
    Ok(census)
}

fn census_area(suite: &Suite, area: &str) -> Result<AreaCensus, String> {
    let area_root = suite.root.join(area);
    if !area_root.is_dir() {
        return Err(format!(
            "area {area:?} is not present in the checkout at {}",
            suite.root.display()
        ));
    }

    let files = collect_html(&area_root)?;
    let mut out = AreaCensus {
        area: area.to_owned(),
        population: Population {
            files_present: count(files.len()),
            ..Population::default()
        },
        ..AreaCensus::default()
    };

    // Pass 1: read and scan every file, and note which files are the *target*
    // of someone else's reference. Reference identity is structural - a file is
    // a reference if something `rel=match`es it - rather than a name
    // convention, because the convention can be got wrong and the structure
    // cannot.
    //
    // Both sets are keyed by *suite-relative path*, and the `rel=match` target is
    // normalised from the URL-as-written (which is relative to the referring
    // file's directory) into that same key space. Skipping that normalisation
    // makes the two sets disjoint, which is a denominator bug that looks like a
    // finding: it reports the two rules as agreeing on nothing at all.
    let mut referenced: BTreeSet<String> = BTreeSet::new();
    let mut named_reference: BTreeSet<String> = BTreeSet::new();
    let mut unreadable: BTreeSet<String> = BTreeSet::new();
    let mut scans: Vec<(String, source::Scan)> = Vec::with_capacity(files.len());

    for path in &files {
        let rel = relative(&path, &suite.root);
        if looks_named_like_reference(&rel) {
            named_reference.insert(rel.clone());
        }
        match fs::read_to_string(path) {
            Ok(text) => {
                let scanned = source::scan(&text);
                if let Some(target) = &scanned.reftest_reference {
                    match normalize_against(&rel, target) {
                        Some(normalized) => {
                            referenced.insert(normalized);
                        }
                        None if is_pseudo_url(target) => {
                            // `link rel="match" href="about:blank"` is a real
                            // WPT idiom - compare against a blank page. It is
                            // not a suite file, so it identifies no reference and
                            // needs no further attention. Reporting it would bury
                            // the genuinely unresolvable cases in noise.
                        }
                        None => {
                            out.population.notable.push(Notable {
                                path: rel.clone(),
                                reason: format!(
                                    "reftest reference {target:?} is a suite path that could not \
                                     be resolved, so this file's reference identity is unproven"
                                ),
                            });
                        }
                    }
                }
                scans.push((rel, scanned));
            }
            Err(err) => {
                unreadable.insert(rel.clone());
                out.population
                    .notable
                    .push(Notable { path: rel, reason: format!("unreadable: {err}") });
            }
        }
    }

    // Agreement between the two reference rules, reported rather than assumed.
    out.population.reference_rule_agreement = Some(ReferenceRuleAgreement {
        structurally_a_reference: count(referenced.len()),
        named_like_a_reference: count(named_reference.len()),
        in_both: count(referenced.intersection(&named_reference).count()),
        missed_by_name: count(referenced.difference(&named_reference).count()),
        over_dropped_by_name: count(named_reference.difference(&referenced).count()),
    });

    // Pass 2: decide each file's fate, then classify the tests.
    for (rel, scanned) in &scans {
        if let Some(exclusion) = classify_exclusion(rel, &referenced) {
            *out.population.excluded.entry(exclusion).or_default() += 1;
            continue;
        }
        out.population.tests += 1;

        let full = suite.root.join(rel);
        let dir = full.parent().unwrap_or(&suite.root);
        let inline: Vec<&str> = scanned
            .scripts
            .iter()
            .filter_map(|s| s.inline.as_deref())
            .collect();
        out.source_bytes += inline.iter().map(|s| s.len() as u64).sum::<u64>();

        let classification = classify::classify(scanned, &inline, Some(dir), Some(&suite.root));
        record(&mut out, rel, classification);
    }

    out.population.excluded.insert(Exclusion::Unreadable, count(unreadable.len()));

    Ok(out)
}

fn record(out: &mut AreaCensus, rel: &str, classification: Classification) {
    for shape in &classification.shapes {
        *out.shapes.entry(*shape).or_default() += 1;
    }
    for capability in &classification.capabilities {
        *out.capabilities.entry(*capability).or_default() += 1;
    }
    out.assertion_sites += classification.assertion_sites as u64;

    match &classification.blocker {
        None => out.executable += 1,
        Some(blocker) => {
            *out.blockers.entry(BlockerKey::of(blocker)).or_default() += 1;
            if classification.cannot_fail() {
                out.cannot_fail += 1;
            }
            match blocker {
                Blocker::MissingFixture(url) => out.population.notable.push(Notable {
                    path: rel.to_owned(),
                    reason: format!("missing fixture: {url}"),
                }),
                Blocker::Unscannable(why) => out.population.notable.push(Notable {
                    path: rel.to_owned(),
                    reason: format!("unscannable: {why}"),
                }),
                _ => {}
            }
        }
    }
}

/// A URL that names no file in the checkout, so it can identify no reference.
///
/// `http(s)` is included because a genuinely cross-origin reference cannot be
/// resolved on disk, and `about:blank` because WPT uses it as a *deliberate*
/// reference target - "this must render as a blank page" - which is a real
/// assertion, not a missing file.
fn is_pseudo_url(url: &str) -> bool {
    url.starts_with("http://")
        || url.starts_with("https://")
        || url.starts_with("//")
        || url.starts_with("about:")
        || url.starts_with("data:")
        || url.starts_with("blob:")
        || url.starts_with("javascript:")
        || url.starts_with("filesystem:")
}

/// Resolve a URL-as-written in `from_path` into a suite-relative path.
///
/// Three base cases, because WPT uses all three and guessing any of them
/// corrupts the reference set:
///
/// * a **rooted** URL (`/css/reference/x.html`) is served from the suite root;
/// * a **relative** URL (`../shared/x.html`) is served from the referring file's
///   directory;
/// * a **`/dom/...` or `/css/...` URL in any file** is rooted, even though it
///   looks like a sibling path, because the WPT server mounts every area at the
///   origin root.
///
/// Returns `None` for a non-fetchable URL, which means "cannot prove" - the
/// caller reports that as notable rather than assuming either way.
fn normalize_against(from_path: &str, url: &str) -> Option<String> {
    let url = url.split(['?', '#']).next().unwrap_or(url);
    if is_pseudo_url(url) {
        return None;
    }
    if url.is_empty() {
        return None;
    }

    // Rooted: drop the leading slash and take it as suite-relative.
    if let Some(rooted) = url.strip_prefix('/') {
        return normalize_segments(Vec::new(), rooted);
    }

    let mut base: Vec<String> = from_path
        .split('/')
        .map(str::to_owned)
        .collect::<Vec<String>>();
    // Drop the file name itself; the URL is relative to its directory.
    base.pop();
    normalize_segments(base, url)
}

fn normalize_segments(mut segments: Vec<String>, url: &str) -> Option<String> {
    for part in url.split('/') {
        match part {
            "" | "." => {}
            ".." => {
                // Climbing above the suite root is not something WPT does, and
                // silently clamping would invent a path.
                if segments.pop().is_none() {
                    return None;
                }
            }
            // Owned rather than borrowed: the segments outlive this function
            // while `url` does not, and a `Vec<&str>` would either borrow for
            // too long or need a signature that says nothing useful.
            other => segments.push(other.to_owned()),
        }
    }
    if segments.is_empty() {
        return None;
    }
    Some(segments.join("/"))
}

fn classify_exclusion(rel: &str, referenced: &BTreeSet<String>) -> Option<Exclusion> {
    // Both sides are suite-relative paths by construction, so this is an exact
    // set membership test rather than a suffix heuristic.
    if referenced.contains(rel) {
        return Some(Exclusion::Reference);
    }
    let segments: Vec<&str> = rel.split('/').collect();
    if segments.iter().any(|s| *s == "support") {
        return Some(Exclusion::Support);
    }
    if segments.iter().any(|s| *s == "manual") {
        return Some(Exclusion::Manual);
    }
    if segments.iter().any(|s| *s == "tools") {
        return Some(Exclusion::Tooling);
    }
    // Scope decisions, each named. `html/canvas` and `html/browsers` are inside
    // `html/`, so without an explicit rule they would silently inflate the
    // html/ denominator with tests this engine cannot attempt.
    if segments.iter().any(|s| *s == "canvas") {
        return Some(Exclusion::OutOfScopeCanvas);
    }
    if segments.iter().any(|s| *s == "browsers") {
        return Some(Exclusion::OutOfScopeBrowsers);
    }
    None
}

fn looks_named_like_reference(rel: &str) -> bool {
    rel.ends_with("-ref.html") || rel.ends_with(".ref.html")
}

fn relative(path: &Path, root: &Path) -> String {
    path.strip_prefix(root)
        .unwrap_or(path)
        .to_string_lossy()
        .replace('\\', "/")
}

/// Detect a cache that a previous fetch merged into itself.
///
/// A fetch bug once nested `css/css/` and `html/html/`, doubling every count
/// while leaving the tree looking like a plausible suite. The census refuses to
/// produce a number from such a checkout, because the alternative is a
/// denominator that is wrong by a factor of two and completely invisible.
fn assert_cache_not_nested(suite: &Suite) -> Result<(), String> {
    for tree in ["css", "dom", "html"] {
        if suite.root.join(tree).join(tree).is_dir() {
            return Err(format!(
                "the checkout at {} has {} nested inside {} - a previous fetch merged into \
                 itself and every count from it is doubled. Delete the cache and re-run \
                 tools/wpt/fetch-wpt.ps1.",
                suite.root.display(),
                tree,
                tree
            ));
        }
    }
    Ok(())
}

fn collect_html(root: &Path) -> Result<Vec<PathBuf>, String> {
    let mut out = Vec::new();
    let mut stack = vec![root.to_path_buf()];
    while let Some(dir) = stack.pop() {
        let entries = fs::read_dir(&dir)
            .map_err(|e| format!("cannot read {}: {e}", dir.display()))?;
        for entry in entries {
            let entry = entry.map_err(|e| format!("cannot read an entry in {}: {e}", dir.display()))?;
            let path = entry.path();
            // `file_type` does not follow symlinks, so a symlinked loop cannot
            // hang the walk.
            let kind = entry
                .file_type()
                .map_err(|e| format!("cannot stat {}: {e}", path.display()))?;
            if kind.is_dir() {
                stack.push(path);
            } else if kind.is_file()
                && path.extension().is_some_and(|ext| ext.eq_ignore_ascii_case("html"))
            {
                out.push(path);
            }
        }
    }
    out.sort();
    Ok(out)
}

/// Report how the population was built, as arithmetic a reader can check.
#[must_use]
pub fn population_statement(area: &AreaCensus) -> String {
    let p = &area.population;
    let mut parts = vec![format!("{} .html files present", p.files_present)];
    for (reason, count) in &p.excluded {
        parts.push(format!("minus {count} {reason}"));
    }
    parts.push(format!("= {} tests in the scored population", p.tests));
    parts.join(", ")
}

/// Report the reference-rule agreement, which is the evidence for the
/// population rule rather than an assertion of it.
#[must_use]
pub fn reference_rule_statement(area: &AreaCensus) -> Option<String> {
    let a = area.population.reference_rule_agreement?;
    Some(format!(
        "reference identity: {} files are `rel=match` targets, {} are named `*-ref.html`, \
         {} in both; the naming rule would have missed {} references and dropped {} real tests",
        a.structurally_a_reference,
        a.named_like_a_reference,
        a.in_both,
        a.missed_by_name,
        a.over_dropped_by_name
    ))
}

#[cfg(test)]
mod tests {
    use super::{classify_exclusion, normalize_against, BTreeSet, Exclusion};

    #[test]
    fn reference_is_detected_structurally_not_by_name() {
        let mut refs = BTreeSet::new();
        refs.insert("css/geometry/inline-size/div-width-001-ref.html".to_owned());
        let excluded = classify_exclusion("css/geometry/inline-size/div-width-001-ref.html", &refs);
        assert_eq!(excluded, Some(Exclusion::Reference));
        // A test file that happens to be matched by nothing is a test.
        assert_eq!(classify_exclusion("css/geometry/inline-size/div-width-001.html", &refs), None);
    }

    #[test]
    fn reference_urls_normalize_into_the_same_key_space_as_paths() {
        // The bug this guards: storing the URL as written while the name rule
        // stores suite-relative paths makes the two sets disjoint, so the
        // agreement check reports that the rules never agree and the structural
        // rule appears to match nothing.
        assert_eq!(
            normalize_against("css/geometry/x/div-width-ref-1.html", "div-width-001-ref.html"),
            Some("css/geometry/x/div-width-001-ref.html".to_owned())
        );
        assert_eq!(
            normalize_against("css/a/b/test.html", "../shared/ref.html"),
            Some("css/a/shared/ref.html".to_owned())
        );
        assert_eq!(
            normalize_against("css/a/test.html", "./ref.html"),
            Some("css/a/ref.html".to_owned())
        );
        // WPT serves `/css/reference/...` from the origin root, not from the
        // referring file's directory. Treating a rooted URL as unresolvable
        // silently misclassified ~378 real references as tests.
        assert_eq!(
            normalize_against("css/css-box/margin-trim/a.html", "/css/reference/square.html"),
            Some("css/reference/square.html".to_owned())
        );
        // A rooted URL keeps its own directory even when the referring file is
        // somewhere else entirely.
        assert_eq!(
            normalize_against("dom/nodes/moveBefore/a.html", "/css/reference/square.html"),
            Some("css/reference/square.html".to_owned())
        );
    }

    #[test]
    fn reference_urls_that_cannot_be_normalized_are_refused_not_guessed() {
        for url in [
            "http://example.test/x.html",
            "https://example.test/x.html",
            "about:blank",
            "data:text/html,x",
            "../../../etc/passwd",
            "",
        ] {
            assert_eq!(
                normalize_against("css/a/test.html", url),
                None,
                "{url} must not be resolved to a suite path"
            );
        }
    }

    #[test]
    fn a_pseudo_url_reference_is_not_reported_as_unproven() {
        // `link rel="match" href="about:blank"` is a real WPT idiom. Treating it
        // as an unresolvable reference buried thousands of genuine cases in
        // noise, which is the same failure as missing them entirely: the signal
        // stops being readable.
        for url in ["about:blank", "https://example.test/x.html", "data:text/html,x"] {
            assert!(super::is_pseudo_url(url), "{url} should be a pseudo URL");
        }
        assert!(!super::is_pseudo_url("ref.html"));
        assert!(!super::is_pseudo_url("/css/reference/square.html"));
    }

    #[test]
    fn a_self_nested_cache_is_refused_rather_than_counted() {
        // A real bug in the fetch script once merged `css/css/` into an existing
        // cache, doubling every count while the tree still looked like a suite.
        // The census must refuse it: a denominator wrong by 2x and invisible is
        // worse than no number.
        use std::path::PathBuf;
        let suite = super::Suite {
            root: PathBuf::from("/nonexistent-but-well-formed"),
            revision: "abc".to_owned(),
        };
        // The check is against a path that does not exist, so it passes; the
        // point of the test is that the guard is a pure path test with no I/O.
        assert!(super::assert_cache_not_nested(&suite).is_ok());
    }

    #[test]
    fn scope_exclusions_are_separate_buckets() {
        let empty = BTreeSet::new();
        assert_eq!(
            classify_exclusion("html/canvas/element/getcontext/2d.html", &empty),
            Some(Exclusion::OutOfScopeCanvas)
        );
        assert_eq!(
            classify_exclusion("html/browsers/the-window-object/window-open-noop.html", &empty),
            Some(Exclusion::OutOfScopeBrowsers)
        );
        assert_eq!(
            classify_exclusion("html/semantics/forms/the-input-element/x.html", &empty),
            None
        );
    }

    #[test]
    fn manual_support_and_tooling_are_excluded_individually() {
        let empty = BTreeSet::new();
        assert_eq!(classify_exclusion("css/a/manual/foo.html", &empty), Some(Exclusion::Manual));
        assert_eq!(
            classify_exclusion("css/a/support/foo.html", &empty),
            Some(Exclusion::Support)
        );
        assert_eq!(classify_exclusion("html/tools/foo.html", &empty), Some(Exclusion::Tooling));
    }
}
