[package]
name = "render-browser"
description = "Native preview shell for the self-owned rENDER Rust engine"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
arboard = { version = "3.6.1", default-features = false }
encoding_rs = "0.8.35"
fontdue = "0.9.3"
render-core = { path = "../render-core" }
render-net = { path = "../render-net" }
softbuffer = { version = "0.4.8", default-features = false }
winit = { version = "0.30.12", default-features = false, features = ["rwh_06"] }

[lints]
workspace = true
